extends RefCounted

const CH0_IDENTITY: String = "0_1_identity"
const CH0_PROLOGUE: String = "0_2_prologue"
const CH0_SNOW_CAMP_ARRIVAL: String = "0_2_snow_camp_arrival"
const CH0_SNOW_PATH_ARRIVAL: String = "0_2_snow_path_arrival"
const CH0_VILLA_GATE_ARRIVAL: String = "0_2_villa_gate_arrival"
const CH0_HALL_ARRIVAL: String = "0_2_hall_arrival"
const CH0_HALL_MEMORY: String = "0_2_hall_memory"

const CH1_STUDY_WAKE: String = "1_1_study_wake"
const CH1_PUZZLE_REASONING: String = "1_1_puzzle_reasoning"
const CH1_MURDER_REQUEST: String = "1_1_murder_request"
const CH1_CRIME_SCENE: String = "1_2_crime_scene"
const CH1_BUTLER_BLOCK_LEAVE: String = "1_3_butler_block_leave"
const CH1_BUTLER_INTRO: String = "1_3_butler_intro"
const CH1_LIGHTHOUSE_REASONING_AFTER: String = "1_6_zhong_lighthouse_resolved"
const CH2_SECOND_REASONING: String = "2_1_second_reasoning"
const CH2_THIRD_SEARCH_INTRO: String = "2_3_third_search_intro"
const CH2_THIRD_SEARCH_TURN: String = "2_3_third_search_turn"
const CH2_THIRD_REASONING: String = "2_4_third_reasoning"
const CH2_MEMORY_FRAGMENTS: String = "2_6_memory_fragments"
const CH3_ROUTE: String = "3_1_route"
const FINALE_DUST: String = "4_1_ending_dust"
const FINALE_GODSLAYER: String = "4_2_ending_godslayer"
const FINALE_CALM: String = "4_3_ending_calm"
const FINALE_CLEAR_SNOW: String = "4_4_ending_clear_snow"
const FINALE_EPILOGUE: String = "4_5_easter_egg"
