extends RefCounted

const HALL: String = "res://scenes/rooms/hall.tscn"
const CH0_BLACK_SCREEN: String = "res://scenes/ch0_prologue/ch0_black_screen.tscn"
const CH0_SNOW_FIELD: String = "res://scenes/ch0_prologue/ch0_snow_field.tscn"
const CH0_LOGO: String = "res://scenes/ch0_prologue/ch0_logo.tscn"
const CH1_STUDY: String = "res://scenes/ch1_snow_villa/ch1_study.tscn"
const CH1_CRIME_SCENE: String = "res://scenes/ch1_snow_villa/ch1_crime_scene_lin_room.tscn"
const CH1_BODY_CG: String = "res://scenes/ch1_snow_villa/ch1_body_cg.tscn"
const HUI_KE_TING: String = "res://scenes/rooms/hui_ke_ting.tscn"
const FIRST_SEARCH_ROOM1: String = "res://scenes/rooms/floor2.tscn"
const FIRST_SEARCH_ROOM2: String = "res://scenes/rooms/room_lin_jiu.tscn"
const SECOND_SEARCH_ROOM: String = "res://scenes/rooms/zhong_yue_lab.tscn"
const NPC: String = "res://scenes/characters/npcs/npc.tscn"
const PROLOGUE_TITLE: String = "res://scenes/chapter_titles/prologue_title.tscn"
const CHAPTER1_TITLE: String = "res://scenes/chapter_titles/chapter1_title.tscn"
const CHAPTER2_TITLE: String = "res://scenes/chapter_titles/chapter2_title.tscn"
const CHAPTER3_TITLE: String = "res://scenes/chapter_titles/chapter3_title.tscn"
const FINALE_TITLE: String = "res://scenes/chapter_titles/finale_title.tscn"
const GAME_COMPLETE: String = "res://scenes/chapter_titles/game_complete.tscn"
const LAB_CORRIDOR_CUTSCENE: String = "res://scenes/ch1_snow_villa/ch1_lab_corridor_cutscene.tscn"
const LAB_CG: String = "res://scenes/ch1_snow_villa/ch1_lab_cg.tscn"
